[Params]
# A-амплитуда сигнала в относительных единицах
A = 1000
# f - частота несущей в Гц
f = 440
# fd - частота дискретизации в Гц
fd = 48000
# От n1 десятичные числа
n1 = 0
# до n2  десятичные числа
n2 = 1024
# Разнос частот для FSK в Гц
df = 100
# Скорость передачи в Бодах
rate = 200
# window size
window = 256
# 0 -> биты random; 1 -> toggle
mode = 0
